---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: person-service-deploy
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
  selector:
    matchLabels:
      app: person-service
  template:
    metadata:
      labels:
        app: person-service
    spec:
      containers:
        - name: person-service
          image: "person-service:1.0.0"
          ports:
            - containerPort: 6060
          readinessProbe:
            tcpSocket:
              port: 6060
            initialDelaySeconds: 30
            periodSeconds: 30
          livenessProbe:
            tcpSocket:
              port: 6060
            initialDelaySeconds: 30
            periodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  name: person-service
  labels:
    app: person-service
spec:
  type: NodePort
  ports:
    -   port: 6060
        nodePort: 30000
        protocol: TCP
        name: person-service-app-port
  selector:
    app: person-service